schema_version: 1

context:
  name: django-typer
  version: "3.8.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_typer-${{ version }}.tar.gz
  sha256: 8fedd0aa684f43e23013831ad614a31a800ea8cb080a63b166b6af0bdfa0bd69

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=4.2,<6.2
    - click >=8.1.8,<8.5
    - typer >=0.23.1,<0.26.0

tests:
  - python:
      imports:
        - django_typer
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"


about:
  homepage: https://github.com/django-commons/django-typer
  summary: Use Typer to define the CLI for your Django management commands.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
