schema_version: 1

context:
  name: django-typer
  version: "3.9.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/django_typer-${{ version }}.tar.gz
  sha256: f11415dee38b27cb5bcc2dabdcebc80d17e84367589ae2be7a67f4572ed53af1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - django >=5.2,<6.2
    - click >=8.1.8,<8.6
    - typer >=0.23.1,<0.26.0

tests:
  - python:
      imports:
        - django_typer
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"


about:
  homepage: https://github.com/django-commons/django-typer
  summary: Use Typer to define the CLI for your Django management commands.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
